FinalProject/Bloggingsite/Bloggingsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('users/',include('users.urls')),
]

FinalProject/Bloggingsite/blogs/urls.py
from django.urls import path
from . import views

app_name ='blogs'
urlpatterns=[
    path('',views.home,name="home"),
    path('about',views.about,name='about'),
    path('myblogs',views.myblogs,name="myblogs"),
    path('post/<int:blog_id>',views.post,name="post"),
    path('new_post',views.new_post,name="new_post"),
    path('edit_post/<int:post_id>',views.edit_post,name="edit_post"),
    path('delete_post/<int:post_id>',views.delete_post,name="delete_post")
]

FinalProject/Bloggingsite/users/urls.py
import django
from django.contrib.auth import views
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from django.urls.conf import include
from . import views
app_name = 'users'
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('mylogin',views.mylogin,name="mylogin"),
    path('register',views.register,name='register'),
    path('logout',views.my_logout,name='my_logout'),
    path('profile/<int:profile_id>',views.profile,name='profile')
]

FinalProject/Bloggingsite/blogs/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import DateTimeField
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_n_time = DateTimeField(auto_now_add=True,null=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    owner = models.ForeignKey(User,on_delete=CASCADE)
    def __t__(self):
        return self.title

FinalProject/Bloggingsite/blogs/forms.py
from django import forms
from django.forms import fields, widgets
from .models import BlogPost
class new_post_form(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title','text']
        widgets = {'text':forms.Textarea(attrs={'cols':100})}
class edit_post_form(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        widgets = {'text':forms.Textarea(attrs={'cols':100})}

FinalProject/Bloggingsite/blogs/views.py
from django.contrib import messages
from django.forms.forms import Form
from django.shortcuts import render,redirect
from .models import BlogPost
from .forms import new_post_form,edit_post_form
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django import http
# Create your views here.
def home(request):
    all_blogs = BlogPost.objects.all().order_by('-date_n_time')
    context = {
        'all_blogs':all_blogs
    }
    return render(request,'blogs/home.html',context)
def about(request):
    return render(request,'blogs/about.html')
# @login_required(login_url='users:login')
def myblogs(request):
    if request.user.is_authenticated    :
        blog_entries = BlogPost.objects.filter(owner = request.user)
        context = {
            'blog_entries':blog_entries
        }
        return render(request,'blogs/myblogs.html',context)
    else:
        messages.error(request,"Please login to continue!")
        return redirect('users:login')
def post(request,blog_id):
    blog_entry = BlogPost.objects.get(id=blog_id)
    context = {
        'blog_entry':blog_entry,'request':request,
    }
    return render(request,'blogs/post.html',context)
# @login_required(login_url='users:login')
def new_post(request):
    if request.user.is_authenticated:
        if request.method!='POST':
            form = new_post_form()
        else:
            form = new_post_form(data=request.POST)
            if form.is_valid():
                post=form.save(commit=False)
                post.owner = request.user
                post.save()
                return redirect('blogs:myblogs')
        #if form was not valid then invalid form or empty form will be available if we reach here!
        context = {
            'form':form
        }
        return render(request,'blogs/new_post.html',context)
    else:
        messages.error(request,"Please login to continue!")
        return redirect('users:login')
# @login_required(login_url='users:login')
def edit_post(request,post_id):
    if request.user.is_authenticated:
        if request.user!=BlogPost.objects.get(id=post_id).owner:
            messages.error(request,"You can not edit other's Blogs!")
            return redirect('blogs:post',blog_id=post_id )
        else:
            if request.method!='POST':
                form = edit_post_form(instance=BlogPost.objects.get(id=post_id))
            else:
                form = edit_post_form(data=request.POST,instance=BlogPost.objects.get(id=post_id))
                if form.is_valid():
                    form.save()
                    return redirect('blogs:post',blog_id=post_id)
            context = {
                'form':form,'id':post_id
            }
            return render(request,'blogs/edit_post.html',context)
    else:
        messages.error(request,"Please login to continue!")
        return redirect('users:login')
# @login_required(login_url='users:login')
def delete_post(request,post_id):
    if request.user.is_authenticated:
        if request.user!=BlogPost.objects.get(id=post_id).owner:
            messages.error(request,"You can not delete other's Blogs!")
            return redirect('blogs:post',blog_id=post_id )
        else:
            BlogPost.objects.get(id=post_id).delete()
            return redirect('blogs:myblogs')
    else:
        messages.error(request,"Please login to continue!")
        return redirect('users:login')

FinalProject/Bloggingsite/blogs/templates/blogs/about.html
{%extends 'blogs/base.html'%}
{%block aboutactive%} active{%endblock aboutactive%}
{%block content%}
<div class="d-flex h-100 text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column mt-0">

    <main class="px-1 py-0">
      <h1>SHort on Time</h1>
      <p class="lead mb-0">No Worries, get going with our <code>sweet and short</code> insightful blogging community!
      </p>
      <p class="lead mb-0">Express yourself and Explore others - Share your Views and seek others'</p>
      <p class="lead my-2">
        <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white" style="color: black;">Learn more</a>
      </p>
    </main>
  </div>
</div>
{%endblock content%}

FinalProject/Bloggingsite/blogs/templates/blogs/base.html
<!-- {%load bootstrap4%} -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Webpage</title>
  <!-- {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %} -->

  <!--External Bootstrap in case needed-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!--External Bootstrap in case needed-->

  {# Display django.contrib.messages as Bootstrap alerts #}
  {% bootstrap_messages %}

  {%block headforlinking%}{%endblock headforlinking%}
</head>

<body>
  {%block navigation%}
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Links -->
    <a class="navbar-brand" href="{%url 'blogs:home'%}"><kbd>SHoT</kbd></a>
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#col-view"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="col-view">
      {%if user.is_authenticated%}
      <a class="nav-item" style="min-width: 3%;" href="{%url 'users:profile' request.user.id%}">
        {{avatar_svg|safe}}
      </a>
      <a class="nav-item" href="{%url 'users:profile' request.user.id %}">
        <kbd>Hello {{user.username}}</kbd>
      </a>
      {%endif%}
      <ul class="navbar-nav justify-content-end">
        <li class="nav-item {%block aboutactive%}{%endblock aboutactive%}">
          <a class="nav-link" href="{%url 'blogs:about'%} ">About</a>
        </li>
        {%if user.is_authenticated%}
        <li class="nav-item {%block myblogsactive%}{%endblock myblogsactive%}">
          <a class="nav-link" href="{%url 'blogs:myblogs'%} ">My Blogs</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link btn" href="{%url 'users:my_logout'%}"">Logout</a>
        </li>
        {%else%}
        <li class=" nav-item {%block loginactive%}{%endblock loginactive%}">
            <a class="nav-link" href="{%url 'users:login'%}" data-toggle="modal" data-target="#loginmodal">Login</a>
        </li>
        <li class="nav-item {%block registeractive%}{%endblock registeractive%}">
          <a class="nav-link" href="{%url 'users:register'%}">Register</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>
 {%block login_modal%}
  <!-- The Login Modal -->
  <!-- <link href={% static "users/register.css" %} rel="stylesheet"> -->
  <div class="modal fade" id="loginmodal">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">New here? Register!</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="form-body">
            <div class="row">
              <div class="form-holder col-12" style="min-height: auto;">
                <div class="">
                  <div class="form-items">
                    <h3 class="col-md-12 text-center">Login To SHoT</h3>
                    <form class="requires-validation" action="{%url 'users:mylogin'%}" method="POST" novalidate>
                      {%csrf_token%}
                      <div class="col-md-12">
                        <input id="login_username" class="form-control" type="text" name="username" placeholder="Username"
                          required>
                        <div class="valid-feedback">Username field is valid!</div>
                        <div class="invalid-feedback">Invalid Username</div>
                      </div>
                      <div class="col-md-12">
                        <input class="form-control" type="password" name="password" placeholder="Password" required>
                        <div class="valid-feedback">Password field is valid!</div>
                        <div class="invalid-feedback">Password field cannot be blank!</div>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="login_invalidCheck" required>
                        <label class="form-check-label" style="color: black;">Keep me signed in</label>
                        <div class="invalid-feedback">Please confirm that the entered data are all correct!</div>
                      </div>
                      <div class="form-button mt-3">
                        <button id="login_submit" type="submit" class="btn btn-primary">Login</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

                  <!-- Modal footer -->
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
 {%endblock login_modal%}

                </div>
              </div>
            </div>
            {%endblock navigation%}
            

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            {%block content%}
            {%endblock content%}
</body>
<script src={% static "blogs/myscripts.js" %} "type=" text/javascript"></script>

</html>

FinalProject/Bloggingsite/blogs/templates/blogs/edit_post.html
{%extends 'blogs/base.html'%}
{%block content%}
<h1>Edit Blogpost!</h1>
<form action="{%url 'blogs:edit_post' id%}" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Edit Post</button>
</form>
{%endblock content%}

FinalProject/Bloggingsite/blogs/templates/blogs/home.html
{%extends 'blogs/base.html'%}
{%load static%}
{%block content%}
{%block headforlinking%}
<link rel="stylesheet" 
href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" 
integrity="sha384- 
 B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" 
  crossorigin="anonymous">
{%endblock headforlinking%}
<div class="jumbotron p-3 p-md-5 text-white bg-dark" style="border-radius: 0px !important;">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>
<div class="row" style="margin: auto !important;" >
  <input type="hidden" id="blogs-total" name="blogs-total" value="{{all_blogs | length}}">
  {%for blog in all_blogs%}
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250" style="min-height: 40vh !important; background: lavenderblush;">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="{%url 'blogs:post' blog.id%}">{{blog.title|title}}</a>
        </h3>
        <h5 style="color: palevioletred;">By <a href="{%url 'users:profile' blog.owner.id%}" style="color: palevioletred;">{{blog.owner.username}}</a></h5>
        <div class="mb-1 text-muted">{{blog.date_n_time}}</div>
        <p class="card-text mb-auto">{{blog.text|truncatewords:20}}</p>
        <a href="{%url 'blogs:post' blog.id%}">Continue reading</a>
      </div>
      <!-- <div class="avatar" style="min-width: 30%;">
        <a href="{%url 'users:profile' blog.owner.id%}">{{blog.owner.user_avatar.avatar_svg|safe}}</a>
      </div> -->
      <input type="hidden" id="username_for_avatar-{{forloop.counter}}" name="username" value="{{ blog.owner }}">
      <input type="hidden" id="blog_id-{{forloop.counter}}" name="blogid" value="{{ blog.id }}">
      <img id="{{blog.id}}" class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 30%; height: 80%;" src="" data-holder-rendered="true"> 
          <div class="card-footer text-center mt-auto">
              <i id="like1" class="fas fa-thumbs-up"></i> <div id="like1-bs3"></div>
              <i id="dislike1" class="fas fa-thumbs-down"></i> <div id="dislike1-bs3"></div>
          </div>
    </div>
  </div>
{%endfor%}
<script src={% static "blogs/home_pp.js" %}></script>
{%endblock content%}

FinalProject/Bloggingsite/blogs/templates/blogs/myblogs.html
{%extends 'blogs/base.html'%}
{%block myblogsactive%} active {%endblock myblogsactive%}
{%block content%}
<div class="row text-center m-0">
<h1 class="col-12" style="padding: 0%;">Blogs you have written:</h1>
<a class="btn btn-dark col-12 mb-2" href="{%url 'blogs:new_post'%}">New Blog Post</a>
{%for blog in blog_entries%}
<div class="col-md-12 mb-2" style="background: mistyrose;">
        <h3 class="mb-0">
          <a class="text-dark" href="{%url 'blogs:post' blog.id%}">{{blog.title|title}}</a>
        </h3>
        <h5 style="color: palevioletred;">By <a href="{%url 'users:profile' blog.owner.id%}" style="color: palevioletred;">{{blog.owner.username}}</a></h5>
        <div class="mb-1 text-muted">{{blog.date_n_time}}</div>
        <p class="card-text mb-auto font-weight-bold" style="font-size: larger;font-family: cursive;">{{blog.text|truncatewords:20}}</p>
        <div class="row">
            <a href="{%url 'blogs:post' blog.id%}" class="col-md-4 btn btn-dark border">Continue reading</a>
        <a class="btn btn-dark col-md-4 border" href="{%url 'blogs:edit_post' blog.id%}">Edit Blog Post</a>
        <a class="btn btn-dark col-md-4 border" href="{%url 'blogs:delete_post' blog.id%}">Delete Blog Post</a>
        </div>
        </div>
{%endfor%}
</div>
{%endblock content%}

FinalProject/Bloggingsite/blogs/templates/blogs/new_post.html
{%extends 'blogs/base.html'%}
{%load static%}
{%block content%}
<h1>Create a new Blogpost!</h1>
<form action="{%url 'blogs:new_post'%}" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Create Post</button>
</form>
{%endblock content%}

FinalProject/Bloggingsite/blogs/templates/blogs/post.html
{%extends "blogs/base.html"%}
{%block content%}
<div class="container text-center">
    <h1 >{{blog_entry.title|title}}</h1>
<p style="font-size: larger;font-family: cursive;">{{blog_entry.text}}</p>
</div>
{%endblock content%}