FinalProject/Bloggingsite/Bloggingsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('users/',include('users.urls')),
]

FinalProject/Bloggingsite/blogs/urls.py
from django.urls import path
from . import views

app_name ='blogs'
urlpatterns=[
    path('',views.home,name="home"),
    path('about',views.about,name='about'),
    path('myblogs',views.myblogs,name="myblogs"),
    path('post/<int:blog_id>',views.post,name="post"),
    path('new_post',views.new_post,name="new_post"),
    path('edit_post/<int:post_id>',views.edit_post,name="edit_post"),
    path('delete_post/<int:post_id>',views.delete_post,name="delete_post")
]

FinalProject/Bloggingsite/users/urls.py
import django
from django.contrib.auth import views
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from django.urls.conf import include
from . import views
app_name = 'users'
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('mylogin',views.mylogin,name="mylogin"),
    path('register',views.register,name='register'),
    path('logout',views.my_logout,name='my_logout'),
    path('profile/<int:profile_id>',views.profile,name='profile')
]

FinalProject/Bloggingsite/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class user_avatar(models.Model):
    user = models.OneToOneField(User,on_delete=CASCADE,null=True)
    avatar_svg = models.TextField(null=True)

FinalProject/Bloggingsite/users/views.py
from blogs.models import BlogPost
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .models import user_avatar
# Create your views here.
def mylogin(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request,"Successfully logged in!")
            return redirect(request.path)
        else:
            messages.error(request,"Invalid Credentials, please try again!")
            return redirect('blogs:home')
    else:
        return redirect('blogs:home')
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
        avatar_data = request.POST.get('avatar_data')
        #check if pass1 == pass2 and other things
        if User.objects.filter(username = username).first():
            messages.error(request, "This username is already taken")
            return redirect('users:register')
        if pass1!=pass2:
            messages.error(request, "Both Passwords didn't match,please try again")
            return redirect('users:register')
        
        user = User.objects.create_user(username,email,pass1)
        avatar = user_avatar.objects.create(user = user)
        avatar.avatar_svg = avatar_data
        user.first_name = fname
        user.last_name = lname
        user.save()
        avatar.save()
        messages.success(request,"You have Registered Successfully!")
        return redirect('blogs:home')
    return render(request,'registration/register.html')
def my_logout(request):
    logout(request)
    messages.success(request,"Successfully Logged Out!")
    return redirect('blogs:home')
def profile(request,profile_id):
    profiled_user = User.objects.get(id = profile_id)
    blogs_by_user = BlogPost.objects.filter(owner=profiled_user)
    print(blogs_by_user)
    context = {
        'user_concerned':User.objects.get(id = profile_id).username,
        'full_name':User.objects.get(id = profile_id).first_name +" " + User.objects.get(id = profile_id).last_name,
        'blogs_by_user': blogs_by_user
    }
    return render(request,'users/userprofile.html', context)

FinalProject/Bloggingsite/users/templates/users/userprofile.html
{%extends 'blogs/base.html'%}
{% load static%}
{%block headforlinking%}
<link rel="stylesheet" href={% static "users/profile.css" %} >
{%endblock headforlinking%}
{%block content%}
<!-- <div class="row-md">
<div class="col-xl-12 order-xl-2 mb-5 mb-xl-0">
    <div class="card card-profile shadow">
      <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
          <div class="card-profile-image">
            <a href="#">
              <img src="" class="rounded-circle" id="pp" alt="Profile avatar">
            </a>
          </div>
        </div>
      </div>
      <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex justify-content-between">
          <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
          <a href="#" class="btn btn-sm btn-info float-right">Message</a>
        </div>
      </div>
      <div class="card-body pt-0 pt-md-4">
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center mt-md-5">
            </div>
          </div>
        </div>
        <div class="text-center">
          <h1>
            {{user_concerned}}
          </h1>
          <input type="hidden" id="username_for_avatar" name="username" value="{{ user_concerned }}">
          <div class="h5 font-weight-300">
            <i class="ni location_pin mr-2"></i>Bucharest, Romania
          </div>
          <div class="h5 mt-4">
            <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
          </div>
          <div>
            <i class="ni education_hat mr-2"></i>University of Computer Science
          </div>
          <hr class="my-4">
          <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.</p>
          <a href="#">Show more</a>
        </div>
      </div>
    </div>
  </div>
</div> -->

<div class="card text-center mt-2">
  <img class="card-img" id="pp" alt="Profile avatar" src="">
  <h1>{{full_name|title}}</h1>
  <input type="hidden" id="username_for_avatar" name="username" value="{{ user_concerned }}">
  <p class="title">Username : <code>{{user_concerned}}</code> </p>
  <p>About</p>
  <p><button>Contact</button></p>
</div>

<div class="row" style="margin: auto !important;" >
  <div class="col-md-12 text-center mt-2"><p style="font-weight:bolder; font-family: cursive; font-size: 200%;">Some Of My Blogs</p></div>
  {%for blog in blogs_by_user%}
  <div class="col-md">
    <div class="card flex-md-row mb-4 box-shadow h-md-250" style="min-height: 40vh !important; background: lavenderblush;">
      <div class="card-body d-flex flex-column align-items-start">
        <h3 class="mb-0">
          <a class="text-dark" href="{%url 'blogs:post' blog.id%}">{{blog.title|title}}</a>
        </h3>
        <h5 style="color: palevioletred;">By <a href="{%url 'users:profile' blog.owner.id%}" style="color: palevioletred;">{{blog.owner.username}}</a></h5>
        <div class="mb-1 text-muted">{{blog.date_n_time}}</div>
        <p class="card-text mb-auto">{{blog.text|truncatewords:20}}</p>
        <a href="{%url 'blogs:post' blog.id%}" style="color: blue;">Continue reading</a>
      </div>
      <!-- <div class="avatar" style="min-width: 30%;">
        <a href="{%url 'users:profile' blog.owner.id%}">{{blog.owner.user_avatar.avatar_svg|safe}}</a>
      </div> -->
      <!-- <input type="hidden" id="username_for_avatar-{{forloop.counter}}" name="username" value="{{ blog.owner }}">
      <input type="hidden" id="blog_id-{{forloop.counter}}" name="blogid" value="{{ blog.id }}">
        <img id="{{blog.id}}" class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 30%; height: 80%;" src="" data-holder-rendered="true">
          <div class="card-footer text-center mt-auto">
              <i id="like1" class="fas fa-thumbs-up"></i> <div id="like1-bs3"></div>
              <i id="dislike1" class="fas fa-thumbs-down"></i> <div id="dislike1-bs3"></div>
          </div> -->
    </div>
  </div>
  {%endfor%}
<script src={%  static "Multiavatar-main/multiavatar.min.js" %} type="text/javascript"></script>
<script src={% static "users/profile.js" %}></script>
{%endblock content%}